- hosts: monitor
  become: yes
  tasks:
    - name: Gather package facts
      package_facts:
        manager: auto
         
    - name: install Docker
      include_tasks:
        file: tasks/install-docker.yml

    - name: Install docker compose
      include_tasks: 
        file: tasks/install-compose.yml
    
    - name: Create prom  & ops directories
      file: 
        src: "{{ item }}"
        state: directory
      with_items: 
        - "{{ prometheus_config_dir }}"
        - "{{ ops_dir }}"
      tags: 
        - install
        
    - name: Getting compose template
      template:
        src: templates/docker-compose.j2
        dest: "{{ ops_dir }}{{ project_dir }}{{ compose_file }}"
      tags:
        - always

    - name: upload prometheus config
      copy: 
        src: files/prometheus.yml 
        dest: "{{ prometheus_config_dir }}"
      tags:
        - always

    - name: Create or update docker-compose stack
      include_tasks: tasks/run-compose.yml
    
          

        


