- hosts: monitor
  become: yes
  tasks:
    - name: Gather package facts
      package_facts:
        manager: auto
         
    - name: install Docker
      include_tasks:
        file: tasks/install-docker.yml

    - name: Install docker compose
      include_tasks: 
        file: tasks/install-compose.yml
    
    - name: Create monitoring & ops directories
      file: 
        path: "{{ item }}"
        state: directory
      with_items: 
        - "{{ prometheus.config_dir }}"
        - "{{ grafana.data_dir }}"
        - "{{ alertmanager.data_dir }}"
        - "{{ ops_dir }}"
        - "{{ ops_dir }}{{ project_dir }}"
      tags: 
        - install
        
    - name: Getting compose template
      template:
        src: templates/docker-compose.j2
        dest: "{{ ops_dir }}{{ project_dir }}{{ compose_file }}"
      tags:
        - install
        - update

    - name: upload prometheus config files
      copy: 
        src: "files/{{ item }}" 
        dest: "{{ prometheus.config_dir }}"
      with_items: "{{ prometheus.config_files }}"
      tags:
        - install
        - update

    - name: Upload Alertmanager configuration files
      copy: 
        src: "files/{{ item }}"
        dest: "{{ alertmanager.config_dir}}"
      with_items: "{{ alertmanager.config_files }}"
      tags:
        - install
        - update

    - name: Create or update docker-compose stack
      include_tasks: tasks/run-compose.yml
    
          

        


