# - name: install Docker compose
#   block:  
#     - name: Install prerequisites for docker-compose
#       package:
#         name: ['python3-pip', 'python3-setuptools', 'virtualenv']

#     - name: Install docker-compose
#       pip:
#         name: docker-compose
#   when: "'docker-compose' not in ansible_facts.packages"
#   tags:
#     - install
#     - compose

block:
  - name: Install compose
    cmd: sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

  - cmd: sudo chmod +x /usr/local/bin/docker-compose
  when: "'docker-compose' not in ansible_facts.packages"
  tags:
    - install
    - compose
