- name: install Docker compose
  block:  
    - name: Install prerequisites for docker-compose
      package:
        name: ['python3-pip', 'python3-setuptools', 'virtualenv']

    - name: Install docker-compose
      pip:
        name: docker-compose
  when: "'docker-compose' not in ansible_facts.packages"
  tags:
    - install
    - compose