- name: update Docker Compose stack
  community.docker.docker_compose:
    project_src: {{ ops-dir }}{{ project-dir }}
    restarted: true
    files:
    - {{ compose-file }}
  tags:
    - update

- name:
  community.docker.docker_compose:
    project_src: {{ ops-dir }}{{ project-dir }}
    present: true
    files:
    - {{ compose-file }}
  tags:
    - install

