- name: Stop Docker Compose stack
  community.docker.docker_compose:
    project_src: "{{ ops_dir }}{{ project_dir }}"
    state: absent
    files:
    - "{{ compose_file }}"

- name: Start Docker Compose stack
  community.docker.docker_compose:
    project_src: "{{ ops_dir }}{{ project_dir }}"
    state: present
    files:
    - "{{ compose_file }}"


