ansible_host: <ip-addr>
ansible_ssh_user: xxxxxx
ops_dir: /opt/devops/
prometheus_config_dir: "{{ ops_dir }}prometheus/"
prometheus_image: prom/prometheus
project_dir: ansible-prom/
compose_file: docker-compose.yml
exposed_prom_port: 9055

