ansible_host: <ip-addr>
ansible_ssh_user: xxxxxx
ops_dir: /opt/devops/
project_dir: ansible-prom/
compose_file: docker-compose.yml

prometheus:
  image: prom/prometheus
  container_name: ""
  port: 9055
  config_dir: "{{ ops_dir }}prometheus/"
  config_files:
    - prometheus.yml

alertmanager:
  container_name: ""
  image: ""
  port: 6060
  config_files:
    - alertmanager.yml

grafana: 
  container_name: ""
  image: ""
  config_files:
    - grafana.yml
  data_dir: ""
  port: 5656

