ansible_host: <ip-addr>
ansible_ssh_user: xxxxxx
ops-dir: /opt/devops/
prometheus-config-dir: "{{ ops-dir }}prometheus"
project-dir: ansible-prom
compose-file: docker-compose.yml
git-repo-path: ""
exposed-prom-port: 9055
