ansible_host: <ip-addr>
ansible_ssh_user: xxxxxx
ops_dir: /opt/test-devops
project_dir: ansible-prom
compose_file: docker-compose.yml
compose_url: https://github.com/docker/compose/releases/download/1.23.2/docker-compose-Linux-x86_64

prometheus:
  image: prom/prometheus
  container_name: prometheus_server_compose
  port: 9055
  #config_dir: "{{ ops_dir }}prometheus_server/etc/prometheus/"
  #data_dir: "{{ ops_dir  }}prometheus_server/prometheus/"
  config_dir: "{{ ops_dir }}/prometheus/"
  data_dir: "{{ ops_dir }}/prometheus_data"
  config_files:
    - prometheus.yml

alertmanager:
  container_name: alertmanager_compose
  image: quay.io/prometheus/alertmanager
  #config_dir: "{{ ops_dir }}alertmanager/etc/alertmanager"
  config_dir: "{{ ops_dir }}/alertmanager/"
  port: 6060
  config_files:
    - alertmanager.yml

grafana: 
  container_name: grafana_server_compose
  image: grafana/grafana
  #data_dir: "{{ ops_dir }}grafana_server/var/lib/grafana"
  data_dir: "{{ ops_dir }}/grafana/"
  port: 5656

